/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'paymentStatus' : IDL.Text,
  'studentName' : IDL.Text,
  'upiTransactionId' : IDL.Text,
  'seatId' : IDL.Nat,
  'bookingDuration' : IDL.Text,
  'bookingDate' : IDL.Text,
  'studentContact' : IDL.Text,
  'roomId' : IDL.Nat,
  'amount' : IDL.Nat,
  'timeSlot' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BookingResult = IDL.Record({
  'studentId' : IDL.Text,
  'bookingId' : IDL.Nat,
  'password' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Room = IDL.Record({
  'id' : IDL.Nat,
  'isAC' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'capacity' : IDL.Nat,
  'condition' : IDL.Text,
});
export const Seat = IDL.Record({
  'id' : IDL.Nat,
  'isAvailable' : IDL.Bool,
  'roomId' : IDL.Nat,
  'seatType' : IDL.Text,
  'seatNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initialize' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'approveBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'createBooking' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
      ],
      [BookingResult],
      [],
    ),
  'getBookedSeatIds' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(IDL.Nat)],
      ['query'],
    ),
  'getBookingByCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Opt(Booking)],
      ['query'],
    ),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
  'getSeat' : IDL.Func([IDL.Nat], [Seat], ['query']),
  'getSeatsByRoom' : IDL.Func([IDL.Nat], [IDL.Vec(Seat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSeatAvailable' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'rejectBooking' : IDL.Func([IDL.Nat], [Booking], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateBookingPayment' : IDL.Func([IDL.Nat, IDL.Text], [Booking], []),
  'updateSeatAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [Seat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'paymentStatus' : IDL.Text,
    'studentName' : IDL.Text,
    'upiTransactionId' : IDL.Text,
    'seatId' : IDL.Nat,
    'bookingDuration' : IDL.Text,
    'bookingDate' : IDL.Text,
    'studentContact' : IDL.Text,
    'roomId' : IDL.Nat,
    'amount' : IDL.Nat,
    'timeSlot' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BookingResult = IDL.Record({
    'studentId' : IDL.Text,
    'bookingId' : IDL.Nat,
    'password' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Room = IDL.Record({
    'id' : IDL.Nat,
    'isAC' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'capacity' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const Seat = IDL.Record({
    'id' : IDL.Nat,
    'isAvailable' : IDL.Bool,
    'roomId' : IDL.Nat,
    'seatType' : IDL.Text,
    'seatNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_initialize' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'approveBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'createBooking' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
        ],
        [BookingResult],
        [],
      ),
    'getBookedSeatIds' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getBookingByCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Opt(Booking)],
        ['query'],
      ),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getRooms' : IDL.Func([], [IDL.Vec(Room)], ['query']),
    'getSeat' : IDL.Func([IDL.Nat], [Seat], ['query']),
    'getSeatsByRoom' : IDL.Func([IDL.Nat], [IDL.Vec(Seat)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSeatAvailable' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'rejectBooking' : IDL.Func([IDL.Nat], [Booking], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateBookingPayment' : IDL.Func([IDL.Nat, IDL.Text], [Booking], []),
    'updateSeatAvailability' : IDL.Func([IDL.Nat, IDL.Bool], [Seat], []),
  });
};

export const init = ({ IDL }) => { return []; };