/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'status' : BookingStatus,
  'paymentStatus' : PaymentStatus,
  'studentName' : string,
  'expiryDate' : string,
  'upiTransactionId' : string,
  'seatId' : bigint,
  'bookingDuration' : string,
  'bookingDate' : string,
  'studentContact' : string,
  'roomId' : bigint,
  'amount' : bigint,
  'timeSlot' : string,
}
export interface BookingResult {
  'studentId' : string,
  'bookingId' : bigint,
  'password' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'expired' : null } |
  { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Message {
  'id' : bigint,
  'status' : MessageStatus,
  'content' : string,
  'bookingId' : bigint,
  'recipient' : string,
  'sender' : string,
  'timestamp' : bigint,
}
export type MessageStatus = { 'read' : null } |
  { 'unread' : null };
export type PaymentStatus = { 'submitted' : null } |
  { 'pending' : null } |
  { 'paid' : null };
export interface Room {
  'id' : bigint,
  'isAC' : boolean,
  'name' : string,
  'description' : string,
  'capacity' : bigint,
  'condition' : string,
}
export interface Seat {
  'id' : bigint,
  'isAvailable' : boolean,
  'roomId' : bigint,
  'seatType' : string,
  'seatNumber' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initialize' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'approveBooking' : ActorMethod<[bigint], Booking>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelBooking' : ActorMethod<[bigint], Booking>,
  'checkAndUpdateBookingExpired' : ActorMethod<[bigint, string], boolean>,
  'createBooking' : ActorMethod<
    [bigint, string, string, string, string, string, string, string, bigint],
    BookingResult
  >,
  'deleteBooking' : ActorMethod<[bigint], boolean>,
  'getBookedSeatIds' : ActorMethod<[string, string], Array<bigint>>,
  'getBookingByCredentials' : ActorMethod<[string, string], [] | [Booking]>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getBookingsByDate' : ActorMethod<[string], Array<Booking>>,
  'getBookingsByStudent' : ActorMethod<[string], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMessagesByBooking' : ActorMethod<[bigint], Array<Message>>,
  'getRooms' : ActorMethod<[], Array<Room>>,
  'getSeat' : ActorMethod<[bigint], Seat>,
  'getSeatsByRoom' : ActorMethod<[bigint], Array<Seat>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSeatAvailable' : ActorMethod<[bigint, string, string], boolean>,
  'markAllMessagesAsRead' : ActorMethod<[string], Array<Message>>,
  'markMessageAsRead' : ActorMethod<[bigint], Message>,
  'rebookSeat' : ActorMethod<[string, string], BookingResult>,
  'rejectBooking' : ActorMethod<[bigint], Booking>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendMessage' : ActorMethod<
    [bigint, string, string, string, bigint],
    Message
  >,
  'updateBookingPayment' : ActorMethod<[bigint, string], Booking>,
  'updateSeatAvailability' : ActorMethod<[bigint, boolean], Seat>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];