/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Seat {
    id: bigint;
    isAvailable: boolean;
    roomId: bigint;
    seatType: string;
    seatNumber: string;
}
export interface Message {
    id: bigint;
    status: MessageStatus;
    content: string;
    bookingId: bigint;
    recipient: string;
    sender: string;
    timestamp: bigint;
}
export interface Room {
    id: bigint;
    isAC: boolean;
    name: string;
    description: string;
    capacity: bigint;
    condition: string;
}
export interface BookingResult {
    studentId: string;
    bookingId: bigint;
    password: string;
}
export interface Booking {
    id: bigint;
    status: BookingStatus;
    paymentStatus: PaymentStatus;
    studentName: string;
    expiryDate: string;
    upiTransactionId: string;
    seatId: bigint;
    bookingDuration: string;
    bookingDate: string;
    studentContact: string;
    roomId: bigint;
    amount: bigint;
    timeSlot: string;
}
export interface UserProfile {
    name: string;
}
export enum BookingStatus {
    cancelled = "cancelled",
    expired = "expired",
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum MessageStatus {
    read = "read",
    unread = "unread"
}
export enum PaymentStatus {
    submitted = "submitted",
    pending = "pending",
    paid = "paid"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    approveBooking(id: bigint): Promise<Booking>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelBooking(id: bigint): Promise<Booking>;
    checkAndUpdateBookingExpired(bookingId: bigint, currentDate: string): Promise<boolean>;
    createBooking(seatId: bigint, studentName: string, studentContact: string, bookingDate: string, expiryDate: string, timeSlot: string, bookingDuration: string, upiTransactionId: string, amount: bigint): Promise<BookingResult>;
    deleteBooking(id: bigint): Promise<boolean>;
    getBookedSeatIds(date: string, timeSlot: string): Promise<Array<bigint>>;
    getBookingByCredentials(studentId: string, password: string): Promise<Booking | null>;
    getBookings(): Promise<Array<Booking>>;
    getBookingsByDate(date: string): Promise<Array<Booking>>;
    getBookingsByStudent(studentId: string): Promise<Array<Booking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMessagesByBooking(bookingId: bigint): Promise<Array<Message>>;
    getRooms(): Promise<Array<Room>>;
    getSeat(id: bigint): Promise<Seat>;
    getSeatsByRoom(roomId: bigint): Promise<Array<Seat>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isSeatAvailable(seatId: bigint, date: string, timeSlot: string): Promise<boolean>;
    markAllMessagesAsRead(studentId: string): Promise<Array<Message>>;
    markMessageAsRead(messageId: bigint): Promise<Message>;
    rebookSeat(studentId: string, password: string): Promise<BookingResult>;
    rejectBooking(id: bigint): Promise<Booking>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    sendMessage(bookingId: bigint, sender: string, recipient: string, content: string, timestamp: bigint): Promise<Message>;
    updateBookingPayment(id: bigint, upiTransactionId: string): Promise<Booking>;
    updateSeatAvailability(id: bigint, isAvailable: boolean): Promise<Seat>;
}
import type { Booking as _Booking, BookingStatus as _BookingStatus, Message as _Message, MessageStatus as _MessageStatus, PaymentStatus as _PaymentStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async approveBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.approveBooking(arg0);
                return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveBooking(arg0);
            return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async checkAndUpdateBookingExpired(arg0: bigint, arg1: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.checkAndUpdateBookingExpired(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkAndUpdateBookingExpired(arg0, arg1);
            return result;
        }
    }
    async createBooking(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: bigint): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteBooking(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteBooking(arg0);
            return result;
        }
    }
    async getBookedSeatIds(arg0: string, arg1: string): Promise<Array<bigint>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookedSeatIds(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookedSeatIds(arg0, arg1);
            return result;
        }
    }
    async getBookingByCredentials(arg0: string, arg1: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingByCredentials(arg0, arg1);
                return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingByCredentials(arg0, arg1);
            return from_candid_opt_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookings();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookings();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByDate(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDate(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDate(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStudent(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStudent(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStudent(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessagesByBooking(arg0: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessagesByBooking(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessagesByBooking(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRooms(): Promise<Array<Room>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRooms();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRooms();
            return result;
        }
    }
    async getSeat(arg0: bigint): Promise<Seat> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeat(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeat(arg0);
            return result;
        }
    }
    async getSeatsByRoom(arg0: bigint): Promise<Array<Seat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSeatsByRoom(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSeatsByRoom(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSeatAvailable(arg0: bigint, arg1: string, arg2: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSeatAvailable(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSeatAvailable(arg0, arg1, arg2);
            return result;
        }
    }
    async markAllMessagesAsRead(arg0: string): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllMessagesAsRead(arg0);
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllMessagesAsRead(arg0);
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async markMessageAsRead(arg0: bigint): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessageAsRead(arg0);
                return from_candid_Message_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessageAsRead(arg0);
            return from_candid_Message_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async rebookSeat(arg0: string, arg1: string): Promise<BookingResult> {
        if (this.processError) {
            try {
                const result = await this.actor.rebookSeat(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rebookSeat(arg0, arg1);
            return result;
        }
    }
    async rejectBooking(arg0: bigint): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectBooking(arg0);
                return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectBooking(arg0);
            return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async sendMessage(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: bigint): Promise<Message> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Message_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Message_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateBookingPayment(arg0: bigint, arg1: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingPayment(arg0, arg1);
                return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingPayment(arg0, arg1);
            return from_candid_Booking_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSeatAvailability(arg0: bigint, arg1: boolean): Promise<Seat> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSeatAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSeatAvailability(arg0, arg1);
            return result;
        }
    }
}
function from_candid_BookingStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Message_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Message {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n1(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _MessageStatus;
    content: string;
    bookingId: bigint;
    recipient: string;
    sender: string;
    timestamp: bigint;
}): {
    id: bigint;
    status: MessageStatus;
    content: string;
    bookingId: bigint;
    recipient: string;
    sender: string;
    timestamp: bigint;
} {
    return {
        id: value.id,
        status: from_candid_MessageStatus_n17(_uploadFile, _downloadFile, value.status),
        content: value.content,
        bookingId: value.bookingId,
        recipient: value.recipient,
        sender: value.sender,
        timestamp: value.timestamp
    };
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _BookingStatus;
    paymentStatus: _PaymentStatus;
    studentName: string;
    expiryDate: string;
    upiTransactionId: string;
    seatId: bigint;
    bookingDuration: string;
    bookingDate: string;
    studentContact: string;
    roomId: bigint;
    amount: bigint;
    timeSlot: string;
}): {
    id: bigint;
    status: BookingStatus;
    paymentStatus: PaymentStatus;
    studentName: string;
    expiryDate: string;
    upiTransactionId: string;
    seatId: bigint;
    bookingDuration: string;
    bookingDate: string;
    studentContact: string;
    roomId: bigint;
    amount: bigint;
    timeSlot: string;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n3(_uploadFile, _downloadFile, value.status),
        paymentStatus: from_candid_PaymentStatus_n5(_uploadFile, _downloadFile, value.paymentStatus),
        studentName: value.studentName,
        expiryDate: value.expiryDate,
        upiTransactionId: value.upiTransactionId,
        seatId: value.seatId,
        bookingDuration: value.bookingDuration,
        bookingDate: value.bookingDate,
        studentContact: value.studentContact,
        roomId: value.roomId,
        amount: value.amount,
        timeSlot: value.timeSlot
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    read: null;
} | {
    unread: null;
}): MessageStatus {
    return "read" in value ? MessageStatus.read : "unread" in value ? MessageStatus.unread : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    expired: null;
} | {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "expired" in value ? BookingStatus.expired : "pending" in value ? BookingStatus.pending : "approved" in value ? BookingStatus.approved : "rejected" in value ? BookingStatus.rejected : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    submitted: null;
} | {
    pending: null;
} | {
    paid: null;
}): PaymentStatus {
    return "submitted" in value ? PaymentStatus.submitted : "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n1(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Array<Message> {
    return value.map((x)=>from_candid_Message_n15(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
